spring:
  application:
    name: solva

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: TRACE

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true